### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tolgatasci** [physicalattraction/PAHappnBot#1]
File "PAHappnUser.py", line 8
    def __init__(self, happn_user: dict):
                                 ^
SyntaxError: invalid syntax

not one error very long invalid syntax

**Comment by physicalattraction** [comment]
Where does this code come from? In the master branch, I see in that line `__init__`, not `init`.

**Comment by tolgatasci** [comment]
I tried to run that file

**Comment by physicalattraction** [comment]
Try checking out the master branch from scratch and run it again. Apparently you made a change to the file somewhere.

**Comment by tolgatasci** [comment]
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import PAHappnBot
  File "C:\Users\tolga\Desktop\PAHappnBot-master (1)\PAHappnBot-master\src\PAHappnBot.py", line 101
    def get_crossings(self, limit=None) -> OrderedDict:
                                        ^
SyntaxError: invalid syntax
```
is not working syntax error

**Comment by physicalattraction** [comment]
Are you using Python 3.4? This syntax is not working in Python 2.7.

**Comment by tolgatasci** [comment]
yes 2.7 i am try 3.4 sryyyy
